---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: 這些已知限制特定於 Amazon Web Services 中的Cloud Volumes ONTAP 。 
---
= AWS 中Cloud Volumes ONTAP的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下已知限制特定於 Amazon Web Services 中的Cloud Volumes ONTAP 。請務必查看link:reference-limitations.html["所有雲端供應商對Cloud Volumes ONTAP的限制"]。



== AWS Outpost 限制

如果您有 AWS Outpost，則可以透過在工作環境精靈中選擇 Outpost VPC 在該 Outpost 中部署Cloud Volumes ONTAP 。體驗與駐留在 AWS 中的任何其他 VPC 相同。請注意，您需要先在 AWS Outpost 中部署連接器。

需要指出的是，存在一些限制：

* 目前僅支援單節點Cloud Volumes ONTAP系統
* 可與Cloud Volumes ONTAP一起使用的 EC2 執行個體僅限於 Outpost 中可用的執行個體
* 目前僅支援通用 SSD（gp2）




== 快閃記憶體快取限制

C5D 和 R5D 實例類型包括本機 NVMe 存儲， Cloud Volumes ONTAP將其用作_Flash Cache_。請注意以下限制：

* 必須在所有磁碟區上停用壓縮才能利用Cloud Volumes ONTAP 9.12.0 之前的 Flash Cache 效能改進。部署或升級至Cloud Volumes ONTAP 9.12.1 時，您無需停用壓縮。
+
您可以在從BlueXP建立磁碟區時選擇無儲存效率，也可以建立磁碟區然後 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["使用 CLI 停用資料壓縮"^]。

* Cloud Volumes ONTAP不支援重新啟動後快取重新預熱。




== Amazon CloudWatch 報告的誤報

Cloud Volumes ONTAP在空閒時不會釋放 CPU，因此 https://aws.amazon.com/cloudwatch/["亞馬遜雲端監控"^]可以報告 EC2 執行個體的高 CPU 警告，因為它看到 100% 的使用率。您可以忽略該警報。  ONTAP統計指令顯示 CPU 的真實使用情況。



== Cloud Volumes ONTAP HA 對不支援立即恢復存儲

節點重啟後，夥伴必須同步資料才能返回儲存。重新同步資料所需的時間取決於節點關閉時客戶端寫入的資料量以及復原期間的資料寫入速度。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html["了解在 AWS 中執行的Cloud Volumes ONTAP HA 對中的儲存運作原理"^] 。
