---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 已知限制標識了該產品的此版本不支援或無法與其正確互通的平台、裝置或功能。仔細審查這些限制。 
---
= 所有雲端供應商中Cloud Volumes ONTAP的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制標識了該產品的此版本不支援或無法與其正確互通的平台、裝置或功能。仔細審查這些限制。

以下限制適用於所有雲端供應商中的Cloud Volumes ONTAP ：AWS、Azure 和 Google Cloud。



== 不支援的ONTAP功能

Cloud Volumes ONTAP不支援以下功能：

* 聚合級線上重複資料刪除
* 聚合級後台重複資料刪除
* 磁碟維護中心
* 磁碟清理
* FabricPool鏡像
* 光纖通道（FC）
* 快閃記憶體池
* 無限卷
* 介面組
* 節點內 LIF 故障轉移
* MetroCluster
* 多管理員驗證
+
在Cloud Volumes ONTAP上啟用多管理員驗證將導致不受支援的設定。

* RAID4、RAID-DP、 RAID-TEC （支援RAID0）
* 服務處理器
* SnapLock Compliance和企業模式（僅支援 Cloud WORM）
* SnapMirror同步
* VLAN
* SMB 持續可用性 (CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["持續可用的 SMB 共享"^]不支援無中斷運作。





== 最大並發複製操作數

無論實例類型或機器類型為何， Cloud Volumes ONTAP 的最大並發SnapMirror或SnapVault傳輸數為每個節點 100 個。



== 雲端提供者快照不得用於您的備份和復原計劃

您不應將雲端提供者的快照用作Cloud Volumes ONTAP資料備份和復原計畫的一部分。您應該始終使用ONTAP Snapshot 副本或第三方備份解決方案來備份和還原託管在Cloud Volumes ONTAP上的資料。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["了解如何使用BlueXP backup and recovery備份和還原ONTAP數據"^] 。


NOTE: WAFL檔案系統中的ONTAP一致性點決定資料一致性。只有ONTAP可以使WAFL檔案系統靜止以進行崩潰一致性備份。



== Cloud Volumes ONTAP僅支援預留和按需 VM 實例

Cloud Volumes ONTAP可以在雲端提供者提供的預留或按需 VM 執行個體上執行。不支援其他類型的 VM 實例。



== 不應使用自動應用程式資源管理解決方案

自動應用程式資源管理解決方案不應管理Cloud Volumes ONTAP系統。這樣做可能會導致更改不受支援的配置。例如，解決方案可能會將Cloud Volumes ONTAP變更為不支援的 VM 執行個體類型。



== 軟體更新必須由BlueXP完成

Cloud Volumes ONTAP的升級必須從BlueXP完成。您不應使用系統管理員或 CLI 升級Cloud Volumes ONTAP 。這樣做會影響系統穩定性。



== 不得從雲端提供者的控制台修改Cloud Volumes ONTAP部署

從雲端提供者的控制台變更Cloud Volumes ONTAP配置會導致設定不受支援。  BlueXP建立和管理的Cloud Volumes ONTAP資源的任何變更都可能影響系統穩定性和 BlueXP 管理系統的能力。


NOTE: 初始部署後，支援修改用於Cloud Volumes ONTAP資源的 Azure 訂閱名稱。



== 磁碟和聚合必須由BlueXP管理

所有磁碟和聚合都必須直接從BlueXP建立和刪除。您不應從其他管理工具執行這些操作。這樣做會影響系統穩定性，妨礙將來添加磁碟的能力，並可能產生冗餘的雲端供應商費用。



== SnapManager許可限制

Cloud Volumes ONTAP支援SnapManager每伺服器許可證。不支援每個儲存系統（ SnapManager套件）許可證。



== 第三方代理和擴展的局限性

Cloud Volumes ONTAP虛擬機器執行個體不支援第三方代理程式和 VM 擴充。
