---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: 這些已知限制特定於 Microsoft Azure 中的Cloud Volumes ONTAP 。 
---
= Azure 中Cloud Volumes ONTAP的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下已知限制特定於 Microsoft Azure 中的Cloud Volumes ONTAP 。請務必查看link:reference-limitations.html["所有雲端供應商對Cloud Volumes ONTAP的限制"]。



== 使用 Azure VM 擴充功能的限制

Cloud Volumes ONTAP不支援 Azure 虛擬機器 (VM) 擴展，因為它們會影響BlueXP管理作業。在部署期間， BlueXP會阻止在您的虛擬機器上安裝任何擴充功能。如果您現有的Cloud Volumes ONTAP VM 上已安裝擴展，請聯絡 Microsoft Azure 支援將其刪除。如需指導，請參閱知識庫 (KB) 文章 https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["Azure VM 管理擴充功能可以安裝到 Cloud Volume ONTAP中嗎？"^]

從 2025 年 7 月 14 日開始，如果在您的Cloud Volumes ONTAP VM 上偵測到 VM 擴展， NetApp將發送電子郵件並在BlueXP中通知您。



== 快閃記憶體快取限制

Cloud Volumes ONTAP使用某些 VM 類型中的本機 NVMe 儲存作為_Flash Cache_。請注意此限制：

* 不支援重啟後快取重新預熱。




== 高可用性部署的局限性

某些區域不支援高可用性 (HA) 對。

https://bluexp.netapp.com/cloud-volumes-global-regions["查看受支援的 Azure 區域列表"^] 。



== 單一可用區域中 HA 部署的限制

從Cloud Volumes ONTAP 9.15.1 開始，您可以在 Azure 中的單一可用區域 (AZ) 中以 HA 模式部署虛擬機器 (VM) 執行個體。有關支援此功能的標準的信息，請參閱 https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["在 Azure 中的單一可用性區域中部署 HA 對"^]。

如果Cloud Volumes ONTAP版本早於 9.15.1 或未符合上述任何條件，則先前利用可用性集的部署模型將生效。這僅適用於 HA 配置。
